public with sharing class TestConstUtil {
    public static final String carPartsJSON = '{'+
	'"car_parts": ['+
	'{'+
	'"Name": "Brake pads",'+
	'"Description": "Brake pads are an essential component of the braking system, they apply friction to the brake rotor to slow or stop the vehicle.",'+
	'"Manufacturer": "Bosch",'+
	'"Code": "BC905",'+
	'"price": "50.99"'+
	'},'+
	'{'+
	'"Name": "Spark plugs",'+
	'"Description": "Spark plugs are an integral component of the ignition system. They provide the spark needed to ignite the air-fuel mixture in the combustion chamber.",'+
	'"Manufacturer": "NGK",'+
	'"Code": "BKR6E",'+
	'"price": "12.99"'+
	'},'+
	'{'+
	'"Name": "Air filter",'+
	'"Description": "The air filter ensures that the air entering the engine is clean and free of debris. This helps to maintain engine performance and prolong engine life.",'+
	'"Manufacturer": "K&N",'+
	'"Code": "33-2031-2",'+
	'"price": "49.99"'+
	'},'+
	'{'+
	'"Name": "Oil filter",'+
	'"Description": "The oil filter removes contaminants from the engine oil, preventing damage to the engine and extending its life.",'+
	'"Manufacturer": "Mobil 1",'+
	'"Code": "M1-110A",'+
	'"price": "14.99"'+
	'}'+
	']'+
	'}';

	
}